config/routes.rb
Xuehua::Application.routes.draw do


  delete  'likes/:resource_name/:resource_id' => "likes#destroy", :as => 'like'
  post    'likes/:resource_name/:resource_id' => "likes#create",  :as => 'like'

  resources :comments,:only => [:destroy,:index]

  devise_for :users,:controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :skip => [:sessions,:registration] do
  end

  devise_scope :user do
    get '/' => 'devise/sessions#new', :as => :root
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => "devise/registrations#new", :as => :new_user_registration
    post 'signup' => "devise/registrations#create", :as => :user_registration
    get '/users/cancle' => "devise/registrations#cancel", :as => :cancel_user_registration
    get '/users/edit' => "devise/registrations#edit", :as => :edit_user_registration 
  end

  resources :pictures do 
    post 'create_comment'
    get 'show_comment'
    get 'get_picture_info'
  end
  resources :users,:only => :show do
    collection  do
      get :start,  :as => :getting_start
      post :start ,:as => :getting_start
      get :account , :as=> :account
      get :bind_auth, :as => :bindding
    end
    resources :albums
  end

  resources :follows ,:only => :index do
    post :create,:as => :create
    delete :destroy,:as => :destroy
  end

  get "/email_confirm" => "home#email_confirm", :as => :password_confirm

  get "/home" => "home#index"

  get "/profile" => "profiles#edit", :as => :profile
  post "/profile" => "profiles#update", :as => :profile
  resources :avatars
  get "/start" => "profiles#start", :as => :getting_start
  post "/start" => "profiles#create", :as => :create_profile

  resources :notifications , :only => [:create, :destroy,:index] do
    collection do
      get :noty_update , :as => :noty_update
    end
  end
end

app/models/profile.rb
#coding: utf-8
class Profile < ActiveRecord::Base
  attr_accessible :bio, :birthday,:gender, :searchable, :user_name,:state,:city,:school,:image_url_small,:avatar
  validates_presence_of :user_name
  validates_length_of :user_name, :within => 2..20
  validates_length_of :bio, :maximum => 1500 , :allow_blank => true
  validates_each :user_name, :school, :state, :city  do |record, attr, value|
    record.errors.add attr, '字段存在非法字符#&^*$% ' if value  =~ /[#\$%\^&\*]+/
  end

  
 
  belongs_to :user
  has_many :avatars

    
end

app/controllers/profiles_controller.rb
#coding:utf-8
class ProfilesController < ApplicationController

  def show
    @user = User.find params[:id]
    @profile = @user.profile || Profile.new
  end

  def edit
    @profile = current_user.profile || Profile.new 
  end
  
  def create
    @profile = current_user.build_profile(params[:profile])
    if @profile.save
         current_user.update_attribute(:getting_started,true)
         redirect_to home_path ,:notice =>  "个人资料修改成功"
    else
         flash[:alert] = "资料出错，请重新检查"
         render :start
    end
  end

  def start
    @profile = Profile.find_or_initialize_by_user_id(current_user.id)
    render :layout => 'devise'
  end



  def update
    @profile = current_user.build_profile params[:profile]
    if @profile.save
      redirect_to account_users_path, :notice => "个人资料修改成功"
    else
      render :edit
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<% content_for :head do %>
<%= javascript_include_tag "profile" %>
<%= javascript_include_tag "avatar" %>
<%= stylesheet_link_tag "avatar" %>
<% end -%>


<h1>编辑你的个人主页</h1>
<div id="profile">

  <%= render :partial => "avatars/form" %>

<%= form_for(@profile,:url => profile_path, :html => {:class => "well form-horizontal"}, :method => :post) do |f| %>
	  <% if @profile.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</h2>
	
	      <ul>
	      <% @profile.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
<p class="control-group">
        <b class="control-label">用户名</b>
    <%= f.text_field :user_name,:class => "controls"  %>
</p>

<p class="control-group">
    <b class="control-label">性别</b>
    <b class="controls" id="gender">
    <%= f.radio_button :gender ,"male",:id => "radio1" ,:checked => true %>
    <%= f.label "男" ,:for => "radio1"%>
    <%= f.radio_button :gender ,"female",:id => "radio2" %>
    <%= f.label "女" ,:for => "radio2"%>
        
    </b>
  </p>
	<p class="control-group" id="birthday">
	  <b class="control-label" >生日</b>
	  	  	<select id="profile_birthday_1i" name="profile[birthday(1i)]" default_value="1999">
			<option value="1912">1912</option>
			<option value="1913">1913</option>
			<option value="1914">1914</option>
			<option value="1915">1915</option>
			<option value="1916">1916</option>
			<option value="1917">1917</option>
			<option value="1918">1918</option>
			<option value="1919">1919</option>
			<option value="1920">1920</option>
			<option value="1921">1921</option>
			<option value="1922">1922</option>
			<option value="1923">1923</option>
			<option value="1924">1924</option>
			<option value="1925">1925</option>
			<option value="1926">1926</option>
			<option value="1927">1927</option>
			<option value="1928">1928</option>
			<option value="1929">1929</option>
			<option value="1930">1930</option>
			<option value="1931">1931</option>
			<option value="1932">1932</option>
			<option value="1933">1933</option>
			<option value="1934">1934</option>
			<option value="1935">1935</option>
			<option value="1936">1936</option>
			<option value="1937">1937</option>
			<option value="1938">1938</option>
			<option value="1939">1939</option>
			<option value="1940">1940</option>
			<option value="1941">1941</option>
			<option value="1942">1942</option>
			<option value="1943">1943</option>
			<option value="1944">1944</option>
			<option value="1945">1945</option>
			<option value="1946">1946</option>
			<option value="1947">1947</option>
			<option value="1948">1948</option>
			<option value="1949">1949</option>
			<option value="1950">1950</option>
			<option value="1951">1951</option>
			<option value="1952">1952</option>
			<option value="1953">1953</option>
			<option value="1954">1954</option>
			<option value="1955">1955</option>
			<option value="1956">1956</option>
			<option value="1957">1957</option>
			<option value="1958">1958</option>
			<option value="1959">1959</option>
			<option value="1960">1960</option>
			<option value="1961">1961</option>
			<option value="1962">1962</option>
			<option value="1963">1963</option>
			<option value="1964">1964</option>
			<option value="1965">1965</option>
			<option value="1966">1966</option>
			<option value="1967">1967</option>
			<option value="1968">1968</option>
			<option value="1969">1969</option>
			<option value="1970">1970</option>
			<option value="1971">1971</option>
			<option value="1972">1972</option>
			<option value="1973">1973</option>
			<option value="1974">1974</option>
			<option value="1975">1975</option>
			<option value="1976">1976</option>
			<option value="1977">1977</option>
			<option value="1978">1978</option>
			<option value="1979">1979</option>
			<option value="1980">1980</option>
			<option value="1981">1981</option>
			<option value="1982">1982</option>
			<option value="1983">1983</option>
			<option value="1984">1984</option>
			<option value="1985">1985</option>
			<option value="1986">1986</option>
			<option value="1987">1987</option>
			<option value="1988">1988</option>
			<option value="1989">1989</option>
			<option value="1990">1990</option>
			<option value="1991">1991</option>
			<option value="1992">1992</option>
			<option value="1993">1993</option>
			<option value="1994">1994</option>
			<option value="1995">1995</option>
			<option value="1996">1996</option>
			<option value="1997">1997</option>
			<option value="1998">1998</option>
			<option value="1999">1999</option>
			<option value="2000">2000</option>
			<option value="2001">2001</option>
			<option value="2002">2002</option>
			<option value="2003">2003</option>
			<option value="2004">2004</option>
		</select>
		 <b class="ymd">年</b>
			<select id="profile_birthday_2i" name="profile[birthday(2i)]">
			<option value="1" selected="selected" >1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
			</select>
			 <b class="ymd">月</b>
			<select id="profile_birthday_3i" name="profile[birthday(3i)]">
			<option selected="selected" value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
			<option value="13">13</option>
			<option value="14">14</option>
			<option value="15">15</option>
			<option value="16">16</option>
			<option value="17">17</option>
			<option value="18">18</option>
			<option value="19">19</option>
			<option value="20">20</option>
			<option value="21">21</option>
			<option value="22">22</option>
			<option value="23">23</option>
			<option value="24">24</option>
			<option value="25">25</option>
			<option value="26">26</option>
			<option value="27">27</option>
			<option value="28">28</option>
			<option value="29">29</option>
			<option value="30">30</option>
			<option value="31">31</option>
			</select>	
			 <b class="ymd">日</b>
	</p>
	
	<p class="control-group" id="region">
	  <b class="control-label">地域</b>
          <%= f.state_select( :state,{
	       :country => :china,
	       :countries => [:china],
               :update => 'city',:selected => @profile.state},:id => "profile_state",:name => "profile[state]").html_safe %>
             <%=  f.city_select( :city ,{ :country => :china, :state => :beijing,:selected => @profile.city},{:id => :city,:selected => @profile.city}).html_safe %>
	</p>
	
	<p class="control-group">
	    <b class="control-label">个人简介</b>
            <%= f.text_area :bio,:class=> :controls %>
	</p>


	
	  <div class="actions">
	    <%= f.submit "保存" ,:class => "btn btn-primary" ,:id=>"submit"%>
	    <%= f.submit "重置表单", :type => :reset ,:class => "btn btn-danger",:id=>"reset" %>
	  </div>
	<% end %>	
	
</div>
<%= link_to 'Back', home_path %>

app/views/profiles/start.html.erb
<% content_for :head do %>
<%= javascript_include_tag "start" %>
<%= javascript_include_tag "profile" %>
<%= javascript_include_tag "avatar" %>
<%= stylesheet_link_tag "avatar" %>
<% end -%>
<%= link_to "登出", destroy_user_session_path, :method => :delete %>
<%= form_for(@profile,:url => create_profile_path, :html => {:class => "well form-horizontal",:id => "start_form"}, :method => :post) do |f| %>
<div class="block_cover">
	<div class="all_block">
			
 <% if @profile.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</h2>
	
	      <ul>
	      <% @profile.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>


	<div class="block">
		  <%= render :partial => "avatars/form" %>
		<p class="control-group">
        <b class="control-label">用户名</b>
   	 	<%= f.text_field :user_name,:class => "controls"  %>
		</p>

		<p class="control-group">
    	<b class="control-label">性别</b>
    	<b class="controls" id="gender">
	    <%= f.radio_button :gender ,"male",:id => "radio1" ,:checked => true %>
	    <%= f.label "男" ,:for => "radio1"%>
	    <%= f.radio_button :gender ,"female",:id => "radio2" %>
	    <%= f.label "女" ,:for => "radio2"%>
	        
	    </b>
	  	</p>
          <p class="control-group">
          <b class="control-label">学校</b>
          <%= f.text_field :school ,:class => "controls"  %>
        </p>
		<p class="control-group" >
	  <b class="control-label">地域</b>
	  	  <b class="controls" id="region">
	  	  	<%= f.state_select( :state,{
	       :country => :china,
	       :countries => [:china],
           :update => 'city',:selected => @profile.state},:id => "profile_state",:name => "profile[state]").html_safe %>
             <%=  f.city_select( :city ,{ :country => :china, :state => :beijing,:selected => @profile.city},{:id => :city,:selected => @profile.city}).html_safe %>
	  	  </b>
     </p>     
	</div>


<div class="block">
  
	<p class="control-group" id="birthday">
	  <b class="control-label" >生日</b>
	  	  	<select id="profile_birthday_1i" name="profile[birthday(1i)]" default_value="1999">
			<option value="1912">1912</option>
			<option value="1913">1913</option>
			<option value="1914">1914</option>
			<option value="1915">1915</option>
			<option value="1916">1916</option>
			<option value="1917">1917</option>
			<option value="1918">1918</option>
			<option value="1919">1919</option>
			<option value="1920">1920</option>
			<option value="1921">1921</option>
			<option value="1922">1922</option>
			<option value="1923">1923</option>
			<option value="1924">1924</option>
			<option value="1925">1925</option>
			<option value="1926">1926</option>
			<option value="1927">1927</option>
			<option value="1928">1928</option>
			<option value="1929">1929</option>
			<option value="1930">1930</option>
			<option value="1931">1931</option>
			<option value="1932">1932</option>
			<option value="1933">1933</option>
			<option value="1934">1934</option>
			<option value="1935">1935</option>
			<option value="1936">1936</option>
			<option value="1937">1937</option>
			<option value="1938">1938</option>
			<option value="1939">1939</option>
			<option value="1940">1940</option>
			<option value="1941">1941</option>
			<option value="1942">1942</option>
			<option value="1943">1943</option>
			<option value="1944">1944</option>
			<option value="1945">1945</option>
			<option value="1946">1946</option>
			<option value="1947">1947</option>
			<option value="1948">1948</option>
			<option value="1949">1949</option>
			<option value="1950">1950</option>
			<option value="1951">1951</option>
			<option value="1952">1952</option>
			<option value="1953">1953</option>
			<option value="1954">1954</option>
			<option value="1955">1955</option>
			<option value="1956">1956</option>
			<option value="1957">1957</option>
			<option value="1958">1958</option>
			<option value="1959">1959</option>
			<option value="1960">1960</option>
			<option value="1961">1961</option>
			<option value="1962">1962</option>
			<option value="1963">1963</option>
			<option value="1964">1964</option>
			<option value="1965">1965</option>
			<option value="1966">1966</option>
			<option value="1967">1967</option>
			<option value="1968">1968</option>
			<option value="1969">1969</option>
			<option value="1970">1970</option>
			<option value="1971">1971</option>
			<option value="1972">1972</option>
			<option value="1973">1973</option>
			<option value="1974">1974</option>
			<option value="1975">1975</option>
			<option value="1976">1976</option>
			<option value="1977">1977</option>
			<option value="1978">1978</option>
			<option value="1979">1979</option>
			<option value="1980">1980</option>
			<option value="1981">1981</option>
			<option value="1982">1982</option>
			<option value="1983">1983</option>
			<option value="1984">1984</option>
			<option value="1985">1985</option>
			<option value="1986">1986</option>
			<option value="1987">1987</option>
			<option value="1988">1988</option>
			<option value="1989">1989</option>
			<option value="1990">1990</option>
			<option value="1991">1991</option>
			<option value="1992">1992</option>
			<option value="1993">1993</option>
			<option value="1994">1994</option>
			<option value="1995">1995</option>
			<option value="1996">1996</option>
			<option value="1997">1997</option>
			<option value="1998">1998</option>
			<option value="1999">1999</option>
			<option value="2000">2000</option>
			<option value="2001">2001</option>
			<option value="2002">2002</option>
			<option value="2003">2003</option>
			<option value="2004">2004</option>
		</select>
		 <b class="ymd">年</b>
			<select id="profile_birthday_2i" name="profile[birthday(2i)]">
			<option value="1" selected="selected" >1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
			</select>
			 <b class="ymd">月</b>
			<select id="profile_birthday_3i" name="profile[birthday(3i)]">
			<option selected="selected" value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			<option value="10">10</option>
			<option value="11">11</option>
			<option value="12">12</option>
			<option value="13">13</option>
			<option value="14">14</option>
			<option value="15">15</option>
			<option value="16">16</option>
			<option value="17">17</option>
			<option value="18">18</option>
			<option value="19">19</option>
			<option value="20">20</option>
			<option value="21">21</option>
			<option value="22">22</option>
			<option value="23">23</option>
			<option value="24">24</option>
			<option value="25">25</option>
			<option value="26">26</option>
			<option value="27">27</option>
			<option value="28">28</option>
			<option value="29">29</option>
			<option value="30">30</option>
			<option value="31">31</option>
			</select>	
			 <b class="ymd">日</b>
	</p>
	
	
	<p class="control-group">
	    <b class="control-label">个人简介</b>
            <%= f.text_area :bio,:class=> :controls %>
	</p>

</div>	  

<div class="block">
  <p>
    兴趣
  </p>
  <p>	<p class="control-group">
	    <b class="control-label"> 隐私</b>
		    <b class="controls" id="privacy">
		    <%= f.radio_button :searchable ,"true",:id => "privacy_1" ,:checked => true %>
		    <%= f.label "允许被陌生人搜索到" ,:for => "privacy_1"%>
		    <%= f.radio_button :gender ,"false",:id => "privacy_2" %>
		    <%= f.label "不允许被陌生人搜索到" ,:for => "privacy_2"%>
		    	
		    </b>
	</p>    

    隐私
  </p>
  <div class="actions">
	    <%= f.submit "保存" ,:class => "btn btn-primary" ,:id=>"submit"%>
	    <%= f.submit "重置表单", :type => :reset ,:class => "btn btn-danger",:id=>"reset" %>
	  </div>
</div>


</div>


</div>
<div class="page_controller">
	<span class="prev_btn"><a href="#">prev</a></span>
	<span class="circle_btn"><a href="#">1</a></span>
	<span class="circle_btn"><a href="#">2</a></span>
	<span class="circle_btn"><a href="#">3</a></span>
	<span class="next_btn"><a href="#">next</a></span>
</div>


<% end %>