config/routes.rb
Xuehua::Application.routes.draw do


  delete  'likes/:resource_name/:resource_id' => "likes#destroy", :as => 'like'
  post    'likes/:resource_name/:resource_id' => "likes#create",  :as => 'like'

  resources :comments,:only => [:destroy,:index]

  devise_for :users,:controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :skip => [:sessions,:registration] do
  end

  devise_scope :user do
    get '/' => 'devise/sessions#new', :as => :root
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => "devise/registrations#new", :as => :new_user_registration
    post 'signup' => "devise/registrations#create", :as => :user_registration
    get '/users/cancle' => "devise/registrations#cancel", :as => :cancel_user_registration
    get '/users/edit' => "devise/registrations#edit", :as => :edit_user_registration 
  end

  resources :pictures do 
    post 'create_comment'
    get 'show_comment'
    get 'get_picture_info'
  end
  resources :users,:only => :show do
    collection  do
      get :start,  :as => :getting_start
      post :start ,:as => :getting_start
      get :account , :as=> :account
      get :bind_auth, :as => :bindding
    end
    resources :albums
  end

  resources :follows ,:only => :index do
    post :create,:as => :create
    delete :destroy,:as => :destroy
  end

  get "/email_confirm" => "home#email_confirm", :as => :password_confirm

  get "/home" => "home#index"

  get "/profile" => "profiles#edit", :as => :profile
  post "/profile" => "profiles#update", :as => :profile
  resources :avatars
  get "/start" => "profiles#start", :as => :getting_start
  post "/start" => "profiles#create", :as => :create_profile

  resources :notifications , :only => [:create, :destroy,:index] do
    collection do
      get :noty_update , :as => :noty_update
    end
  end
end

app/models/avatar.rb
#coding: utf-8
require 'RMagick'

class Avatar < ActiveRecord::Base
  
  #Paperclip configuration.
  has_attached_file :logo,
                      :styles => AvatarsForRails.avatarable_styles,
                      :default_url => "/assets/logos/:style/:subtype_class.png"

  before_post_process :process_precrop
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :name,:updating_logo,:drag,:drag_name
  validates_attachment_presence :logo, :if => :uploading_file?, :message => "缺少必要的文件"
  attr_accessible :drag,:logo,:crop_x, :crop_y, :crop_w, :crop_h, :name
  after_validation :precrop_done

  belongs_to AvatarsForRails.avatarable_model

  scope :active, where(:active => true)

  before_create :make_active
  after_create :disable_old

  #This method helps when changing the active logo for a user.
  def make_active
    self.updating_logo = true
    self.active = true
  end

  #Disable all the user's logos except the actual.
  def disable_old
    self.avatarable.avatars.where("id != ?", self.id).each do |old_logo|
      old_logo.update_attribute :active, false
    end
  end

  def avatarable
    __send__ AvatarsForRails.avatarable_model
  end

  def uploading_file?
    return @name.blank?
  end

  #Process the seccond step. It makes the precrop of the image and create a new avatar with the croped image.
  def precrop_done

    return if @name.blank? || !@updating_logo.blank?

    precrop_path = File.join(Avatar.images_tmp_path,@name)
    make_precrop(precrop_path,@crop_x.to_i,@crop_y.to_i,@crop_w.to_i,@crop_h.to_i)
    self.logo = File.open(precrop_path)
    FileUtils.remove_file(precrop_path)
  end

  #Returns the avatars_for_rails temp directory.
  def self.images_tmp_path
    tmp_path = File.join(Rails.root, 'public', AvatarsForRails.tmp_path)
    FileUtils.mkdir_p(tmp_path)
    tmp_path
  end

  def self.image_tmp_path(tmp_image)
    File.join '/', AvatarsForRails.tmp_path, tmp_image
  end

  #This method copies a file to the avatars_for_rails temp directory.
  def self.copy_to_temp_file(path)
    FileUtils.cp(path,Avatar.images_tmp_path)
  end

  #Returns the height and widht of an image.
  def self.get_image_dimensions(name)
    img_orig = Magick::Image.read(name).first
    dimensions = {}
    dimensions[:width] =  img_orig.columns
    dimensions[:height] = img_orig.rows
    dimensions
  end

  #Checks if a file is valid for being an avatar.
  def self.check_image_tmp_valid(path)

    begin
      path = File.join(Avatar.images_tmp_path,path)
      img_orig = Magick::Image.read(path).first
      return true
    rescue
    return false
    end
  end

  #Process the image in the first step of the process. It resizes the image and copy it to the avatars_for_rails temp directory.
  def process_precrop

    if @name.blank? && (  logo.content_type.present? && !logo.content_type.start_with?("image/"))
      logo.errors['invalid_type'] = I18n.t('avatar.error.no_image_file')
    return false
    end

    return if !@name.blank?

    if resize_image(logo.queued_for_write[:original].path,500,500)
      logo.errors['precrop'] = "You have to make precrop"
      Avatar.copy_to_temp_file(logo.queued_for_write[:original].path)
    else

    end
  end

  #Resizes an image with the options passed as arguments.
  def resize_image(path,width,height)
    begin
      img_orig = Magick::Image.read(path).first
      img_orig = img_orig.resize_to_fit(width, height)
      img_orig.write(path)
      return true
    rescue
      logo.errors['invalid_type'] = I18n.t('avatar.error.no_image_file')
    return false
    end
  end

  #Precrop an image with the options passed as arguments.
  def make_precrop(path,x,y,width,height)
    begin
      img_orig = Magick::Image.read(path).first
    rescue
      logo.errors['invalid_type'] = I18n.t('avatar.error.no_image_file')
    return false
    end

    dimensions = Avatar.get_image_dimensions(path)

    unless (width == 0) || (height == 0)
      crop_args = [x,y,width,height]
    img_orig = img_orig.crop(*crop_args)
    end

    img_orig = img_orig.resize_to_fill(500,500)

    img_orig.write(path)
  end
end

app/controllers/avatars_controller.rb
#coding: utf-8
class AvatarsController < ApplicationController
  
  #Apply the filters configured in avatars_for_rails initializer
  before_filter :apply_existing_filters
  
  def index
    @avatars = current_avatarable_object.avatars

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @avatars = Avatar.all
    @avatar = Avatar.create(params[:avatar])
    if params[:drag_name].blank?
      respond_to do |format|
        format.html # new.html.erb
      end
    else
      if Avatar.check_image_tmp_valid(params[:drag_name].to_s)
        render :partial => 'precrop'
      else
        @avatar.logo.errors['invalid_type'] = I18n.t('avatar.error.no_image_file')
        render :partial => 'errors'
      end
    end

  end

  def update

    if !current_avatarable_object.avatars.blank?

      new_logo = Avatar.find(params[:id])

      if (new_logo.avatarable == current_avatarable_object)
        actual_logo = current_avatarable_object.avatars.active.first
        unless actual_logo.blank?
          return if new_logo == actual_logo
          old_logo_id = actual_logo.id
          current_avatarable_object.avatars.each do |old_logo|
            old_logo.active = false
            old_logo.save
          end
        else
          old_logo_id = params[:id].to_s
        end

        new_logo.active = true
        new_logo.save

        respond_to do |format|
          format.js { render :layout=>false , :locals=>{:new_id => params[:id],:old_id => old_logo_id}}
        end

      end
    end
  end

  def create
    @avatar = current_avatarable_object.avatars.create(params[:avatar])

    if @avatar.new_record?
      if (params[:avatar].blank? || params[:avatar][:drag].nil?)
        render :new, :layout => false
      else
        render :json => {:name => File.basename(@avatar.logo.queued_for_write[:original].path) }
      end
    else
      respond_to do |format|
        format.js {render :notice => "头像上传成功",:layout => false ,:locals => {:new_id => @avatar.id}}
      end
    end
  end

  def destroy
    @avatar = Avatar.find(params[:id])

    if (@avatar.avatarable == current_avatarable_object)
      @avatar.destroy
      respond_to do |format|
        format.js { render :layout=>false , :locals=>{:deleted_id => params[:id]}}
      end
    end
  end

  def current_avatarable_object
    __send__ AvatarsForRails.current_avatarable_object
  end
  
  def apply_existing_filters
    AvatarsForRails.avatarable_filters.each do |filter|
      __send__ filter
    end
  end
  
end

app/views/avatars/_errors.html.erb
<br class="clearfloat" />

<% unless @avatar.logo.errors["invalid_type"].blank?%>
  <%= @avatar.logo.errors["invalid_type"]%>
<% end %>

app/views/avatars/_form.html.erb
<div id ="avatars_for_rails">
<!--  
<div class= "block">
    <div class = "content">
      <%= form_for Avatar.new,:html => { :multipart => true,:id =>"uploadForm"} do |f| %>
        <div class="form_row">
          <%= f.file_field :logo %>

          <%= f.submit t('avatar.upload'), :class => "button" %>
        </div>
        <div id= "prueba">
        </div>
      <% end %>
    </div>
  
  </div>
-->
<div class="avatar_image">
  <%= current_avatar %>
</div>


  <div class="files"> 
    <%= form_for Avatar.new, :html => { :class => "upload", :multipart => true } do |f| %>
      <%= f.file_field :logo, :id=> "avatar_logo_drag" %>
      <!--<div>Upload files</div>-->
      <%= f.hidden_field :drag %>
    <% end %>

    <table class="upload_files"></table>
    <table class="download_files"></table>
    <div id="show_pic"></div>
    <div id="show_crop"></div>
  </div>

  <div id= "precrop_drag_response"></div>
</div>


<% content_for :javascript do%>
$(document).ready(function() { 
    var options = { 
        target: '#precrop_drag_response',
        success: showResponse
    }; 
 
    $('#uploadForm').submit(function() { 
        $(this).ajaxSubmit(options); 
        return false; 
    }); 
}); 

function update_crop(coords) {
  var rx = 100/coords.w;
  var ry = 100/coords.h;
  
  if((coords.w == 0) || (coords.h == 0)){
    rx = 100/$("#cropImage").width();
    ry = 100/$("#cropImage").height();
    coords.x = 0;
    coords.y = 0;
  }  
  
  $('#preview').css({
    width: Math.round(rx * $("#cropImage").width()) + 'px',
    height: Math.round(ry * $("#cropImage").height()) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = 1;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}

function showResponse(responseText, statusText, xhr, $form)  { 
        jQuery('#cropImage').Jcrop({
            bgColor:     'clear',
            bgOpacity:   .6,
            setSelect:   [ 0, 0, 200, 200 ],
            aspectRatio: 1 ,
            onChange: update_crop,
            onSelect: update_crop
        }); 
} 





  $(function () {
      $('.upload').fileUploadUI({
          uploadTable: $('.upload_files'),
          downloadTable: $('.download_files'),
          buildUploadRow: function (files, index) {
              var file = files[index];
              return $('<tr><td>' + file.name + '<\/td>' +
                      '<td class="file_upload_progress"><div><\/div><\/td>' +
                      '<td class="file_upload_cancel">' +
                      '<div class="ui-state-default ui-corner-all ui-state-hover" title="Cancel">' +
                      '<span class="ui-icon ui-icon-cancel">Cancel<\/span>' +
                      '<\/div><\/td><\/tr>');
          },
          buildDownloadRow: function (file) {
              
          },
          onComplete: function (event, files, index, xhr, handler) { 
             $.ajax({
                type: "GET",
                url: "/avatars/new/?drag_name=" + handler.response.name,
                success: function(data){
                         $("#precrop_drag_response").html(data);
                                 jQuery('#cropImage').Jcrop({
                                    bgColor:     'clear',
                                    bgOpacity:   .6,
                                    setSelect:   [ 0, 0, 200, 200 ],
                                    aspectRatio: 1 ,
                                    onChange: update_crop,
                                    onSelect: update_crop
                                }); 
                         }
                });
          }
      });
  }); 







 <% end %>

app/views/avatars/_list.html.erb
<br class="clearfloat" />
<div class="space_center"></div>
<div class="space_center"></div>
<% unless(@avatars.empty? || (@avatars.first.present? && @avatars.first.id.blank?)) %>
  <h2><%=t('avatar.text.use') %></h2>
  <div class="space_center"></div>
  <div class="space_center"></div>
  <div class="avatars" id="all_avatars">
  <% @avatars.each do |avatar| %>
    <% unless avatar.id.blank? %>
      <%= div_for(avatar) do %>
        <div class="boxgrid captionfull">
          <%= image_tag(avatar.logo.url(:user), :class => avatar.active ? 'default' : 'non_default', :size => '94x94', :id => "avatar_img_#{avatar.id}") %>
          <div class="cover boxcaption"> 
            <%= link_to t('avatar.set_default'), avatar, :confirm => "设置为默认", :method => :put, :remote => true, :id => "avatar_link_#{avatar.id}", :style => avatar.active ? 'display:none;': 'display:solid;' %>
            <%= link_to t('avatar.destroy'), avatar, :confirm => "删除", :method => :delete, :remote => true %>
          </div>  
         </div>        
      <% end %>
      <% end %>
  <% end %>
  </div>
  <br />
  <br class="clearfloat" />
  <div class="space_center"></div>
  <div class="space_center"></div>
  <h2><%=t('avatar.text.new') %></h2>
<% else %>
  <h2><%= t('avatar.new') %></h2>
<% end %>

app/views/avatars/_new.html.erb
<% if !@avatar.logo.errors['precrop'].blank? %>
	<%= render :partial => 'precrop' %>
<% elsif !@avatar.errors.blank? %>
  <%= render :partial => 'errors' %>
<% else %>
<% end %>

app/views/avatars/_precrop.html.erb
<% if params[:drag_name].blank? %>
  <% my_file_name = File.basename(@avatar.logo.queued_for_write[:original].path.to_s) %>
<% else %>
  <% my_file_name = params[:drag_name].to_s %>
<% end %>

<% if Avatar.check_image_tmp_valid(my_file_name) %>
  <div class = "block">
    <div id="precropPrev" >
      <div class="form_row">
        <%= t('avatar.preview') %>
      </div>
      <div id="precropPrevImg" class="logo">
        <%= image_tag Avatar.image_tmp_path(my_file_name) ,:id=>"preview" %>
      </div>  
    </div>
    
    <div class="form_row">
      <%= t('avatar.original') %>
    </div>
    
    <div id="precropDiv" class = "block title content">
    	<%= image_tag Avatar.image_tmp_path(my_file_name) ,:id=>"cropImage" %>
    </div>
  </div>
  
  <%= form_for @avatar, :html => { :multipart => true, :id => "crop_avatar" },:remote => true do |f| %>
  <div class= "block">
    <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
      <%= f.hidden_field attribute, :id => attribute %>
    <% end %>
  	<%= f.hidden_field :name, :value => my_file_name %>
  	  <div class="form_row center">
    <%= f.submit "提交", :class => "button" %>
    </div>
    </div>
  <% end %>
<% end %>

app/views/avatars/create.js.erb
$(function(){
  var kk = $("#current_avatar_img").attr("src",'<%= current_user.avatars.where(:active=> true).first.logo.url(:user) %>');
})

app/views/avatars/destroy.js.erb
$("#avatar_<%= deleted_id %>").remove();

app/views/avatars/edit.html.erb
<h1>Editing logo</h1>

<%= render 'form' %>

<%= link_to 'Show', @avatar %> |
<%= link_to 'Back', avatars_path %>

app/views/avatars/index.html.erb
<%= render :partial => 'list' %>
<%= render :partial => 'form' %>

app/views/avatars/new.html.erb
<%= render :partial => 'new' %>

app/views/avatars/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_avatar_path(@avatar) %> |
<%= link_to 'Back', avatars_path %>

app/views/avatars/update.js.erb
$("#avatar_img_<%= old_id %>").removeClass("default");
$("#avatar_img_<%= old_id %>").addClass("non_default");
$("#avatar_link_<%= old_id %>").show();

$("#avatar_img_<%= new_id %>").removeClass("non_default");
$("#avatar_img_<%= new_id %>").addClass("default");
$("#avatar_link_<%= new_id %>").hide();

$("#current_avatar_img").attr('src', $("#avatar_img_<%= new_id %>").attr('src') );