config/routes.rb
Xuehua::Application.routes.draw do


  delete  'likes/:resource_name/:resource_id' => "likes#destroy", :as => 'like'
  post    'likes/:resource_name/:resource_id' => "likes#create",  :as => 'like'

  resources :comments,:only => [:destroy,:index]

  devise_for :users,:controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :skip => [:sessions,:registration] do
  end

  devise_scope :user do
    get '/' => 'devise/sessions#new', :as => :root
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'signup' => "devise/registrations#new", :as => :new_user_registration
    post 'signup' => "devise/registrations#create", :as => :user_registration
    get '/users/cancle' => "devise/registrations#cancel", :as => :cancel_user_registration
    get '/users/edit' => "devise/registrations#edit", :as => :edit_user_registration 
  end

  resources :pictures do 
    post 'create_comment'
    get 'show_comment'
    get 'get_picture_info'
  end
  resources :users,:only => :show do
    collection  do
      get :start,  :as => :getting_start
      post :start ,:as => :getting_start
      get :account , :as=> :account
      get :bind_auth, :as => :bindding
    end
    resources :albums
  end

  resources :follows ,:only => :index do
    post :create,:as => :create
    delete :destroy,:as => :destroy
  end

  get "/email_confirm" => "home#email_confirm", :as => :password_confirm

  get "/home" => "home#index"

  get "/profile" => "profiles#edit", :as => :profile
  post "/profile" => "profiles#update", :as => :profile
  resources :avatars
  get "/start" => "profiles#start", :as => :getting_start
  post "/start" => "profiles#create", :as => :create_profile

  resources :notifications , :only => [:create, :destroy,:index] do
    collection do
      get :noty_update , :as => :noty_update
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <title><%= yield(:page_title).empty? ? "雪花街" : yield(:page_title)  %></title>
  <%= favicon_link_tag "favicon.ico" %>
  <%=yield :head%>
  <script type="text/javascript" charset="utf-8">
      $(document).ready(function() {
        <%= yield :javascript %>
      })
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="bodyWrapper">
     <div id="nav" class="navbar navbar-fixed-top">
     	<div class="navbar-inner">
   			 <div class="container">
   			 	 	<div id="brand"><a href="#"><img src="/assets/logo.jpg"/></a> </div>
			    	
			        <div id="top-account">
			        	<ul class="nav">
                                          <% if current_user %>
			        		<li><%=link_to "首页", home_path %></li> 
			        		<li><%=link_to "个人主页", user_path(current_user) %></li>
			        		<li><%=link_to "关注", user_path(current_user) %></li>       	
                                          <% end %>
			        	</ul>
			      
			  
					<div id="account">
						<img src="#" />
						<a href="#">chengbapi</a>
						<ul>
							<li><a href="#">个人资料</a></li>
							<li><a href="#">帐号管理</a></li>
                                                        <li><%= link_to "登出", destroy_user_session_path,:method => :delete%></li>
						</ul>
						<span class="caret"></span>
					</div>
					<span class="divider-vertical" style="float: right"></span>
					 <form class="navbar-search pull-right">
  						<input type="text" class="search-query" placeholder="搜索">
					</form>
					<span class="divider-vertical" style="float: right"></span>
					<div id="notification">
			        	<div class="num">
					
			        	</div>
			        	<div class="noti">
			        		<ul>
			        			<li><h4>通知</h4><img class="loading"src="assets/loading.gif" /></li>
			        			<li><a href="#">sb</a>action<div class='cancel'></div></li>
			        			<li><a href="#">sb</a>action<div class='cancel'></div></li>
			        			<li><a href="#">sb</a>action<div class='cancel'></div></li>
			        		</ul>
			        	</div>
			        </div>
			        </div>
			     </div>
   			 </div>
   		</div>
  

     <div id="containner">
         <% flash.each do |name, msg| %>
          <div id="flash">
           <div class="<%= name %>">
             <%= msg %>
            <div class='cancel'></div>
           </div>
          </div>
         <% end %>
        <%= yield %>
     </div>
     <div id="footer">
     	<ul>
     		<li><a href="#">关于</a></li>
     		<li><a href="#">游戏</a></li>
     		<li><a href="#">手机</a></li>
     		<li><a href="#">客服帮忙</a></li>
     		<li><a href="#">隐私</a></li>
     	</ul>   
       人人网©2012
北京千橡网景科技发展有限公司：文网文[2009]169号·京ICP证090254号·京公网安备110000000009号·甲测资字11002066·文化部监督电子邮箱：wlwh@vip.sina.com
     
     
     </div>
  </div>
	<div id="lightboxOverlay" ></div>
	<div class="showpic">
		<div class="left_column">
			<div class="prev arrow"></div>
			<div class="next arrow"></div>
		</div>
                <div class="right_column">
                        <div class="author_information"></div>
                        <div class="description"></div>
                        <div class="comments"></div>
			<div class="cancelbox"></div>
		</div>
	</div>
	<div class="upload_form">
		<div>
			<%=render :partial => 'pictures/upload'%>
			<div class="cancelbox"></div>
		</div>
	</div>
</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <title><%= yield(:page_title) || "雪花街" %></title>
  <%= favicon_link_tag "favicon.ico" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="bodyWrapper">
    <div id="flash">
      <% flash.each do |name, msg| %>
           <div class="<%= name %>">
             <%= msg %>
           </div>
         <% end %>
    </div>
       </div>
     <div id="containner">
        <%= yield %>
     </div>
     <div id="footer">
     	<ul>
     		<li><a href="#">关于</a></li>
     		<li><a href="#">游戏</a></li>
     		<li><a href="#">手机</a></li>
     		<li><a href="#">客服帮忙</a></li>
     		<li><a href="#">隐私</a></li>
     	</ul>   
     	
       人人网©2012
北京千橡网景科技发展有限公司：文网文[2009]169号·京ICP证090254号·京公网安备110000000009号·甲测资字11002066·文化部监督电子邮箱：wlwh@vip.sina.com
     </div>
  </div>
</body>
</html>